### ISSUE TITLE
Question about parallelizing over multiple GPUs

### ISSUE THREAD

**Issue by brianysoong** [broadinstitute/Tangram#69]
Hello! 

I don't have much experience using PyTorch, and I was wondering if Tangram could be easily modified to parallelize over multiple GPUs? I am trying to map onto a spatial dataset which is quite large (~500k cells) and am running into this error: 

```
RuntimeError: CUDA out of memory. 
Tried to allocate 52.38 GiB (GPU 0; 39.59 GiB total capacity; 
860.74 MiB already allocated; 
37.90 GiB free; 
882.00 MiB reserved in total by PyTorch) 
If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  
See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

The GPUs I am using have a 40GB capacity so this error makes sense to me. Is there a way to split across 2 GPUs in PyTorch? I also understand that using `mode = "cluster"` can help alleviate the processing resources required, but was curious about this issue nonetheless. 

Thank you!

**Comment by caiquanyou** [comment]
I have the same question , how to deploy on muti GPU

**Comment by HeesooSong** [comment]
Same! It would be awesome to have the option to parallelize the calculation over multiple GPUs

**Comment by dyyjenny** [comment]
Same! Data is too large to store on one gpu :(

**Comment by Yujing-Bio** [comment]
Same! Too large to store on one gpu

**Comment by cmubioinformatics** [comment]
same, how to use on two or more gpu

![Image](https://github.com/user-attachments/assets/0da3e2f3-0446-4aff-80e9-ff86014679f2)

**Comment by Yujing-Bio** [comment]
I end up just rent a 96VRAM GPU from lambda cloud service, it worked like a charm

**Comment by cmubioinformatics** [comment]
> I end up just rent a 96VRAM GPU from lambda cloud service, it worked like a charm

good advice, but I don't have money, just a poor student.

**Comment by cmubioinformatics** [comment]
Just a suggestion for following poor gay, recently I am doing cell segmentation, cellpose supply a method to make a big image to several small image, after seg, merge the outcomes, not sure whether tangram support this

**Comment by HXD3D0323** [comment]
One sample with 38780 cells, only an 80G A100 didn't work...
